Task end
NBFM/SimbirsoftUI pull request #1
Opened 2022-02-15 21:31 UTC by NBFM

2022-02-17 05:57 UTC, Leo1034 requested changes

2022-02-17 05:57 UTC, Leo1034 commented on src/main/java/pages/YandexMainPage.java
> +public class YandexMainPage extends DriverConfig {
В твоем случае, DriverConfig что-то вроде базового класса. От него должны наследоваться классы с тестами, а классы страниц должны принимать driver во время создания объекта страницы.

2022-02-17 05:57 UTC, Leo1034 commented on src/main/java/pages/YandexMainPage.java
> +    public YandexPassportPage clickLoginBtn() {
Лучше сделать один шаг, авторизация, который будет принимать логин и пароль.

2022-02-17 05:57 UTC, Leo1034 commented on src/main/java/pages/YandexMailPage.java
> +
Обрати внимание на CodeStyle.

2022-02-17 06:43 UTC, NBFM commented on src/main/java/pages/YandexMainPage.java
> +public class YandexMainPage extends DriverConfig {
Исправлено

2022-02-17 07:25 UTC, NBFM commented on src/main/java/pages/YandexMainPage.java
> +    public YandexPassportPage clickLoginBtn() {
Исправлено

2022-02-18 19:09 UTC, Leo1034 requested changes

2022-02-18 19:09 UTC, Leo1034 commented on src/main/java/pages/YandexMailPage.java
> +    private final By writeEmailBtn = By.xpath("//a[@class='mail-ComposeButton js-main-action-compose']");
Поиск элементов лучше реализовать при помощи аннотации @FindBy

2022-02-18 19:09 UTC, Leo1034 commented on src/main/java/configuration/DriverConfig.java
> +    public YandexMainPage openYandex() {
Этот метод не нужен.

2022-02-18 19:09 UTC, Leo1034 commented on src/test/java/UITests/uiTest.java
> +        openYandex()
Здесь сначала создаешь страницу и потом вызываешь ее методы.

2022-02-19 00:20 UTC, closed without merging